In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
np.random.seed(seed=42)

from collections import Counter

In [2]:
salestrain = pd.read_csv('C:\\Users\\Rose\\Desktop\\Capstone3\\sales_train.csv')

In [3]:
items = pd.read_csv('C:\\Users\\Rose\\Desktop\\Capstone3\\items.csv')

In [4]:
#ps4 item categories list
ps4 = pd.read_csv('C:\\Users\\Rose\\Desktop\\Capstone3\\ps4console.csv')
ps4

      item_category_name  item_category_id
0  Игровые консоли - PS4                12

In [5]:
#Joining item_name and item_category_name using item_category_id
ps4info = pd.merge(items, ps4, on='item_category_id')
ps4info

,item_name,item_id,item_category_id,item_category_name
0,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4
1,Sony PlayStation 4 (500 Gb) Black (CUH-1008A/1...,6675,12,Игровые консоли - PS4
2,Sony PlayStation 4 (500 Gb) Black (CUH-1208A/B01),6676,12,Игровые консоли - PS4
3,Sony PlayStation 4 (500 Gb) White (CUH-1108A),6677,12,Игровые консоли - PS4
4,Sony PlayStation 4 (500 Gb) White (CUH-1208A/B01),6678,12,Игровые консоли - PS4
5,Sony PlayStation 4 (500 Gb) Юбилейное издание ...,6679,12,Игровые консоли - PS4
6,Комплект Sony PS4 (500 Gb) Black (CUH-1108A/B0...,13440,12,Игровые консоли - PS4
7,Комплект Sony PS4 (500 Gb) Black (CUH-1108A/B0...,13441,12,Игровые консоли - PS4
8,Комплект Sony PS4 (500 Gb) Black (CUH-1108A/B0...,13442,12,Игровые консоли - PS4
9,Комплект Sony PS4 (500 Gb) Black (CUH-1108A/B0...,13443,12,Игровые консоли - PS4
10,Комплект Sony PS4 (500 Gb) Black (CUH-1108A/B0...,13444,12,Игровые консоли - PS4
11,Комплект Sony PlayStation 4 (1Tb) Black (CUH-1...,13445,12,Игровые консоли - PS4
12,Комплект Sony PlayStation 4 (1Tb) Black (CUH-1...,13446,12,Игровые консоли - PS4
13,Комплект Sony PlayStation 4 (1Tb) Black (CUH-1...,13447,12,Игровые консоли - PS4
14,Комплект Sony PlayStation 4 (1Tb) Black (CUH-1...,13448,12,Игровые консоли - PS4
15,Комплект Sony PlayStation 4 (500 Gb) Black (CU...,13449,12,Игровые консоли - PS4
16,Комплект «Sony PS4 (500 Gb) Black (CUH-1108A/B...,13498,12,Игровые консоли - PS4
17,Комплект «Sony PS4 (500 Gb) White (CUH-1208A)....,13499,12,Игровые консоли - PS4
18,Комплект «Sony PlayStation 4 (1Tb) Black (CUH-...,13503,12,Игровые консоли - PS4
19,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4

In [6]:
#Joining item_name and item_category_name using item_id
ps4sales = pd.merge(ps4info, salestrain , on='item_id')
ps4sales

,item_name,item_id,item_category_id,item_category_name,date,date_block_num,shop_id,item_price,item_cnt_day
0,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,25.08.2015,31,46,29990.0,1.0
1,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,31.08.2015,31,46,29990.0,1.0
2,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,28.08.2015,31,47,29990.0,2.0
3,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,29.08.2015,31,47,29990.0,1.0
4,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,27.08.2015,31,42,29990.0,1.0
...,...,...,...,...,...,...,...,...,...
7397,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,08.09.2015,32,37,999.0,1.0
7398,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,02.09.2015,32,12,999.0,2.0
7399,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,04.09.2015,32,12,999.0,-2.0
7400,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,13.09.2015,32,12,999.0,-1.0
7401,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,15.09.2015,32,12,999.0,1.0

In [7]:
ps4sales.describe()

,item_id,item_category_id,date_block_num,shop_id,item_price,item_cnt_day
count,7402.000000,7402.0,7402.000000,7402.000000,7402.000000,7402.000000
mean,8322.938530,12.0,19.870846,31.735882,22889.299108,1.787355
std,2907.283267,0.0,5.742087,16.561182,3768.189388,3.821714
min,6674.000000,12.0,10.000000,2.000000,999.000000,-3.000000
25%,6675.000000,12.0,15.000000,18.000000,20191.000000,1.000000
50%,6675.000000,12.0,20.000000,31.000000,22990.000000,1.000000
75%,6677.000000,12.0,23.000000,46.000000,24990.000000,1.000000
max,13532.000000,12.0,33.000000,59.000000,34990.000000,101.000000

In [8]:
ps42015 = ps4sales.query('date.str.contains("2015")', engine='python')
ps42015

,item_name,item_id,item_category_id,item_category_name,date,date_block_num,shop_id,item_price,item_cnt_day
0,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,25.08.2015,31,46,29990.0,1.0
1,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,31.08.2015,31,46,29990.0,1.0
2,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,28.08.2015,31,47,29990.0,2.0
3,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,29.08.2015,31,47,29990.0,1.0
4,Sony PlayStation 4 (1Tb) Black (CUH-1208B),6674,12,Игровые консоли - PS4,27.08.2015,31,42,29990.0,1.0
...,...,...,...,...,...,...,...,...,...
7397,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,08.09.2015,32,37,999.0,1.0
7398,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,02.09.2015,32,12,999.0,2.0
7399,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,04.09.2015,32,12,999.0,-2.0
7400,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,13.09.2015,32,12,999.0,-1.0
7401,Комплект предзаказа на консоль Sony PlayStatio...,13532,12,Игровые консоли - PS4,15.09.2015,32,12,999.0,1.0

In [ ]:
grouped.

In [9]:
ps42015.groupby('item_category_name')['item_price'].mean()

item_category_name
Игровые консоли - PS4    26936.049696
Name: item_price, dtype: float64